apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: timescale-db-v15
    meta.helm.sh/release-namespace: db
  labels:
    app: timescale-db-v15
    app.kubernetes.io/component: timescaledb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: timescale-db-v15
    app.kubernetes.io/version: 0.33.1
    chart: timescaledb-single-0.33.1
    cluster-name: timescale-db-v15
    heritage: Helm
    release: timescale-db-v15
    role: master
    type: db
  name: timescale-db-v15-external
  namespace: db
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 9000
    protocol: TCP
    targetPort: postgresql
  selector:
    app: timescale-db-v15
    cluster-name: timescale-db-v15
    role: master
  type: ClusterIP
