apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-airflow
  name: prometheus-airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-airflow
  template:
    metadata:
      labels:
        app: prometheus-airflow
    spec:
      #initContainers:
      #- name: prometheus-data-permission-fix
      #  image: busybox
      #  command: ["/bin/chmod","-R","777", "/data"]
      #  volumeMounts:
      #  - name: prometheus-data
      #    mountPath: /data    
      containers:
      - image: quay.io/prometheus/prometheus:v2.43.0
        name: prometheus-airflow
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        #- "--storage.local.path=/prometheus"
        #- "--storage.tsdb.retention.time=200d"
        - "--storage.tsdb.retention=12h"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: config-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      nodeSelector:
        e2asv5: "true"
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"      
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          name: prometheus-airflow-config
        name: config-volume
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-airflow-config
  labels:
    app: prometheus-airflow
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      scrape_timeout: 5s
    # alerting:
    #  alertmanagers:
    #  - scheme : "http"
    #  - api_version: "v1"
    #  - static_configs:
    #    - targets: 
    #      - 'isg-alertmanager:9093'
    #rule_files:
    #- "promethus_rules.yml"
    scrape_configs:
    - job_name: 'statsd-exporter'
      static_configs:
        - targets: ['statsd-exporter.airflow:9102']