apiVersion: v1
kind: Service
metadata:
  labels:
    app: statsd-exporter
  name: statsd-exporter
spec:
  ports:
    - name: "9102"
      port: 9102
      targetPort: 9102
    - name: "9125"
      port: 9125
      targetPort: 9125
  selector:
    app: statsd-exporter
