apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-perf-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-perf-consumer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka-perf-consumer
    spec:
      containers:
      - command: ["bash", "-c"]
        args: ["while true; do kafka-consumer-perf-test.sh \
                --topic test-topic \
                --group my-group --messages=500 \
                --bootstrap-server kafka-all-broker:29092; sleep 10; done"]
        image: docker.io/bitnami/kafka:2.7.0-debian-10-r50
        name: perf-consumer
