apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-pvc-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: "managed-csi-premium-zrs"
