apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  generation: 1
  name: letsencrypt-issuer
spec:
  acme:
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-issuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
    - http01:
        ingress:
          class: nginx-dev
