apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-producer
  name: java-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-producer
  template:
    metadata:
      labels:
        app: java-kafka-producer
    spec:
      containers:
      - name: java-kafka-producer
        image: quay.io/strimzi-examples/java-kafka-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: kafka-all-broker:29092
          - name: TOPIC
            value: test-topic
          - name: DELAY_MS
            value: "10"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: PRODUCER_ACKS
            value: "all"
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100
