apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: test-topic
spec:
  clusterRef:
    name: kafka
  name: test-topic
  partitions: 20
  replicationFactor: 1
  #config:
  #  "retention.ms": "10"
  #  "cleanup.policy": "delete"
