apiVersion: v1
kind: Service
metadata:
  labels:
    redissp: "true"
    app: redis-sp-dev
    type: dbdev
  name: redis-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    name: internal
  # - port: 9010
  #   protocol: TCP
  #   targetPort: 6379
  #   name: external
  selector:
    app: redis-sp-dev
  sessionAffinity: None
  type: LoadBalancer
