apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-sp-dev
  labels:
    redissp: "true"
    type: dbdev
    app: redis-sp-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: managed-csi-premium-zrs
