apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: active-event-processor-topic
spec:
  clusterRef:
    name: kafka
  name: active-event-processor-topic
  partitions: 10
  replicationFactor: 2
  config:
    "retention.ms": "180000"
    "cleanup.policy": "delete"
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: sms-topic
spec:
  clusterRef:
    name: kafka
  name: sms-topic
  partitions: 10
  replicationFactor: 2
  config:
    "retention.ms": "180000"
    "cleanup.policy": "delete"
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: pts-mail-profile
spec:
  clusterRef:
    name: kafka
  name: pts-mail-profile
  partitions: 10
  replicationFactor: 2
  config:
    "retention.ms": "180000"
    "cleanup.policy": "delete"
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: pts-sms-profile
spec:
  clusterRef:
    name: kafka
  name: pts-sms-profile
  partitions: 10
  replicationFactor: 2
  config:
    "retention.ms": "180000"
    "cleanup.policy": "delete"