apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaTopic
metadata:
  name: test-topic
spec:
  clusterRef:
    name: kafka
  name: test-topic
  partitions: 10
  replicationFactor: 2
  config:
    "retention.ms": "3600000"
    "cleanup.policy": "delete"
