apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: airflow-dev
    type: airflow-dev
  name: airflow-dev
  namespace: dbdev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
  - get
  - watch
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments/status
  verbs:
  - get
  # - list
  # - watch
  # - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: airflow-dev
    type: airflow-dev
  name: airflow-dev
  namespace: dbdev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-dev
subjects:
- kind: ServiceAccount
  name: airflow-dev
  namespace: airflow-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-dev-reader
rules:
- apiGroups: 
  - ""
  resources: 
  - pods
  verbs: 
  - get 
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
  - deployments
  - statefulsets
  verbs:
  - list
  - get
  - watch
- apiGroups: 
  - "metrics.k8s.io"
  resources: 
  - pods
  verbs: 
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-dev-reader-binding
roleRef:
  kind: ClusterRole
  name: airflow-dev-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: airflow-dev
  namespace: airflow-dev
